
image: alpine:latest

alpine:
  script:
    - ls -al / 

py37:
  image: python:3.7
  script:
  - python --version
  
py36:
  image: python:3.6
  script:
  - python --version

hw21_ngspice:
  image: hw21/ngspice 
  script:
  - ngspice -v 


