
# NOTE: runner-token must be template-expanded for this to work! 
#  The GitLab-CI/ GKE combination can't seem to do this naturally:
#  https://gitlab.com/gitlab-org/gitlab-runner/issues/2458
#  So for now, we just `sed` it in locally in `create_config.sh`. 

concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "hw21-kube-gitlab-runner"
  url = "https://gitlab.com/"
  token = "HW21_GITLAB_RUNNER_TOKEN" 
  executor = "kubernetes"
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.kubernetes]
    host = ""
    bearer_token_overwrite_allowed = false
    image = "alpine:latest"
    namespace = ""
    namespace_overwrite_allowed = ""
    privileged = false
    service_account_overwrite_allowed = ""
    pod_annotations_overwrite_allowed = ""
    [runners.kubernetes.volumes]

